name: Go

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.15, 1.16]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Test
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: go build -v ./...

